# Generated by Django 3.1.4 on 2022-09-11 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tareas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='0', max_length=128)),
                ('fecha_creacion', models.DateField(default=datetime.date.today)),
                ('fecha_entrega', models.DateField(default=datetime.date.today)),
                ('usuario_responsable', models.CharField(default='0', max_length=128)),
                ('estado_tarea', models.CharField(default='Programada', max_length=128)),
            ],
        ),
    ]
